/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(malahitpp_control.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d44af44f0f34c254ba9fe497142b8e60)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <malahit/malahitpp_control.h>
// pydoc.h is automatically generated in the build directory
#include <malahitpp_control_pydoc.h>

void bind_malahitpp_control(py::module& m)
{

    using malahitpp_control    = ::gr::malahit::malahitpp_control;


    py::class_<malahitpp_control, gr::block, gr::basic_block,
        std::shared_ptr<malahitpp_control>>(m, "malahitpp_control", D(malahitpp_control))

        .def(py::init(&malahitpp_control::make),
           D(malahitpp_control,make)
        )
        




        .def("set_freq",&malahitpp_control::set_freq,
            py::arg("freq"),
            D(malahitpp_control,set_freq)
        )


        .def("set_lna",&malahitpp_control::set_lna,
            py::arg("gain"),
            D(malahitpp_control,set_lna)
        )


        .def("set_mixer_gain",&malahitpp_control::set_mixer_gain,
            py::arg("gain"),
            D(malahitpp_control,set_mixer_gain)
        )


        .def("set_if_gain",&malahitpp_control::set_if_gain,
            py::arg("gain"),
            D(malahitpp_control,set_if_gain)
        )

        ;




}







