/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(malahit_control.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(96e3f06ede3ffcde1ced38d0da7212be)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <malahit/malahit_control.h>
// pydoc.h is automatically generated in the build directory
#include <malahit_control_pydoc.h>

void bind_malahit_control(py::module& m)
{

    using malahit_control    = ::gr::malahit::malahit_control;


    py::class_<malahit_control, gr::block, gr::basic_block,
        std::shared_ptr<malahit_control>>(m, "malahit_control", D(malahit_control))

        .def(py::init(&malahit_control::make),
           D(malahit_control,make)
        )

        .def("set_freq",&malahit_control::set_freq,
            py::arg("freq"),
            D(malahit_control,set_freq)
        )

        ;

}







